language: ruby
rvm: 2.2.3
cache: bundler
before_script:
  - psql -c 'create database osm_game_test;' -U postgres
  - cp config/secrets.example.yml config/secrets.yml
  - psql -U postgres -c "create extension postgis"
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
services:
  - postgresql
  - redis-server
