# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c7c0f841a59e5bd0934d35053752bd38ff1d013b2034183c762f3ea3439dfb76d95e1a95e9ace296a0437a8e289f4b021e863249cf0b213fe769c24e77ffb17

test:
  secret_key_base: ce395ef32dcb02f05c463fc36f384f76e1e5c3240728d6de35d0961eeb89e2ef28addc90a2d6d8ea651034509b8b658e93e2aa826d2e167fb5442cc1f6cf4683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
